-- Iron Trap leaderboard setup / migration.
-- Run in Supabase > SQL Editor. This keeps the earlier leaderboard compatible.
create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 16),
  score integer not null check (score >= 0),
  floor integer not null default 50 check (floor between 1 and 50),
  time_seconds integer not null default 1 check (time_seconds between 1 and 86400),
  difficulty text not null check (difficulty in ('easy','normal','hard','nightmare','demon')),
  rank text not null default 'S' check (rank in ('D','C','B','A','S')),
  streak integer not null default 0,
  player_id text not null default '',
  completion_seconds integer,
  created_at timestamptz not null default now()
);
alter table public.leaderboard add column if not exists player_id text not null default '';
alter table public.leaderboard add column if not exists completion_seconds integer;
update public.leaderboard set completion_seconds=time_seconds where completion_seconds is null and floor=50;
alter table public.leaderboard drop constraint if exists leaderboard_difficulty_check;
update public.leaderboard set difficulty = case difficulty
  when 'story' then 'easy' when 'rising' then 'normal' when 'pro' then 'hard' when 'elite' then 'nightmare'
  else difficulty end;
alter table public.leaderboard add constraint leaderboard_difficulty_check
  check (difficulty in ('easy','normal','hard','nightmare','demon'));
create index if not exists leaderboard_score_idx on public.leaderboard (score desc, completion_seconds asc);
create index if not exists leaderboard_time_idx on public.leaderboard (completion_seconds asc, score desc);
create index if not exists leaderboard_created_idx on public.leaderboard (created_at desc);
alter table public.leaderboard enable row level security;
-- The browser never talks directly to this table; Netlify Functions use the service role.
